### ISSUE TITLE
How to raise the "Lock file found" event ?

### ISSUE THREAD

**Issue by prigal** [liebig/cron#43]
Hi,
I don't understand why the cron.lock is not deleted sometimes without errors, is there a way to raise the "Lock file found" event so I can send me a mail to check what's is wrong ?
Thanks,
Pierre.

**Comment by pierrerigal** [comment]
First time today I received a mail from my production server "Lock file found" ;)

Everything is OK.

**Comment by liebig** [comment]
That are great news. Thank you for the reply ;)
