### ISSUE TITLE
Getting warning: Lock file found

### ISSUE THREAD

**Issue by tcarpenter2014** [liebig/cron#50]
Hi,
My liebig cron jobs are no longer running and I have not changed any settings on my server.  The issue seemingly started to occur shortly after I did a composer update for this 3-4 weeks back. I am currently getting the following logged to the laravel log:

dev.WARNING: Lock file found - Cron is still running and prevent job overlapping is enabled - second Cron run will be terminated.

Any ideas on what is causing this and how I can fix it? Which lock file is being referenced here?

Thanks,
Troy

**Comment by liebig** [comment]
Closed due to inactivity.
