### ISSUE TITLE
Corn job execute only once 

### ISSUE THREAD

**Issue by NageshA** [liebig/cron#51]
Iam using your example code in global.php
Event::listen('cron.collectJobs', function() {
   
	Cron::add('send email', '* * * * *', function() {
		mail('abc@gmail.com', 'My Subject', 'message');
        return null;
    });

	
    Cron::add('disabled job', '0 * * * *', function() {
        // Do some crazy things successfully every hour
    }, false);
});

And when I do http:root/cron.php?key=$key

only Once cron job will execute and table also get updated once.How to execute this function every minute ?

**Comment by liebig** [comment]
Closed due to inactivity.
