### ISSUE TITLE
Lock File

### ISSUE THREAD

**Issue by mnek84** [liebig/cron#56]
I have this configuration

1 - cronjob (every 1 hour) 
2 - cronjob( everny 10 minutes)

if the 1 cronjob takes 30minutes to run, the second is going to be executed in this period 3 time's or not because is locked ?

**Comment by liebig** [comment]
Thanks for using Cron. If prevent overlapping is enabled, only one Cron instance can run at the same time. So your second job will not run until the first job is done. You can disable this feature easily with the command `Cron::setDisablePreventOverlapping();`. Please note, that you have to configure the [max-execution-time](http://php.net/manual/en/info.configuration.php#ini.max-execution-time) or the PHP script will not run 30 minutes.

**Comment by mnek84** [comment]
ok, great! i pressume that was happening, i should create my own lock for that first Job then!

**Comment by liebig** [comment]
Yes, this seems to be the best way,
