### ISSUE TITLE
Could not find driver only in cron

### ISSUE THREAD

**Issue by louposk** [liebig/cron#58]
Hello,
i have a controller from which i connect to an sql server and i get some results.
Where i run the function using the web interface, the function runs with no problem.

my controller:
```
class ProductController extends \BaseController {
public function __construct(Setting $setting, SqlServer $sqlserver, Opencart $opencart)
	{
		$this->setting = $setting;
		$this->sqlserver = $sqlserver;
		$this->connectionOC = 'localOC';
	}
public function addNewProducts() {
		$opencart = $this->connectionOC;
		$t = $this->setting->getLastProductTimestamp(); 

		$products = $this->sqlserver->getSeries();
return $products;
}
}
```

The cron:
```
Event::listen('cron.collectJobs', function() {
    Cron::add('AddNewProducts', '* * * * *', function() {
        $pr = App::make('ProductController')->addNewProducts();
    });

});
```

If run php artisan cron:run and i get in db log "Exception in job AddNewProducts: could not find driver".
I have tested the previous connection eg. $this->setting->getLast..... and it works.
The error comes drom sqlserver connection, it seems that it cannot find the driver which is already set and working all over the other application.

What am i doing wrong?

Thanks
-Konstantinos

**Comment by liebig** [comment]
Hi @louposk,

I am sorry for the exception and I will try to help you. But first please tell me if you you use Laravel 4 or Laravel 5? Can you show me the complete Exception stack trace and can you tell me in which line the Exception is thrown?

Maybe there is a problem with the dependency injection if you call the application from command shell. Can you test Cron's integrated route and please test with curl: `curl http://yourdomain.com/cron.php?key=yourSecurityKey > /dev/null 2>&1`.

Thanks,
Marc

**Comment by louposk** [comment]
I am using laravel 4.
Where should i find the exception stack? In laravel logs, only get the cron log that says that there was an error. No other info.

Also, i dont have a cron security key. Should i add one?

**Comment by louposk** [comment]
I will try the route with curl and i will come back. Thanks

**Comment by liebig** [comment]
You are right, there is no chance to get the stack trace. I changed this, so now Cron will log the full stack trace of an exception. Please update Cron to head and print the stack trace here.

For testing you can use a simple route like:
``´php
Route::get('/testCron', function() {

    Cron::add('AddNewProducts', '* * * * *', function() {
        $pr = App::make('ProductController')->addNewProducts();
        var_dump($pr);
    });
    
    var_dump(Cron::run());
});
```
If this works, please generate a key and test with curl.

**Comment by louposk** [comment]
Hi @liebig 
the route works. 
```
array (size=6)
  'rundate' => int 1425550450
  'inTime' => boolean false
  'runtime' => float 78.723502159119
  'errors' => int 0
  'crons' => 
    array (size=1)
      0 => 
        array (size=3)
          'name' => string 'AddNewProducts' (length=14)
          'return' => null
          'runtime' => float 78.721502065659
  'lastRun' => 
    array (size=2)
      'rundate' => string '2015-03-05 10:13:14' (length=19)
      'runtime' => float 0.0099999997764826
```
So maybe the driver cannot be run from the artisan command line?

Also, the curl command works just fine

**Comment by liebig** [comment]
That are great news. It seems that the Laravel IoC Container does not work properly if you call it from command line. So I would use the curl command to run Cron. Thanks for your reply.
