### ISSUE TITLE
Unable to run cron

### ISSUE THREAD

**Issue by olso** [liebig/cron#59]
Hey,

```$ * * * * * /usr/bin/php $HOME/Documents/etm/api/artisan cron:run```

gives me

```zsh: command not found: app```

~~Maybe, zsh is the culprit here?~~

**edit1:** same with bash

```$ * * * * * /usr/bin/php $HOME/Documents/etm/api/artisan cron:run```
```No command 'app' found, but there are 17 similar ones```
```app: command not found```

**edit2:** reading http://askubuntu.com/questions/23009/reasons-why-crontab-does-not-work
**edit3:** just going to use external service...

**Comment by liebig** [comment]
Hi @olso,

Thank you for this information. You can use curl instead of an external service, too. `curl http://yourdomain.com/cron.php?key=yourSecurityKey > /dev/null 2>&1`. If you use this, please let me know if it works.

Thanks,
Marc
