### ISSUE TITLE
cron:list

### ISSUE THREAD

**Issue by damage838** [liebig/cron#63]
Hello,

i've installed cron on laravel 5. 
When i run> php artisan cron:list i get 
+---------+------------+-----------+
| Jobname | Expression | Activated |
+---------+------------+-----------+
X-Powered-By: PHP/5.6.5
Content-type: text/html; charset=UTF-8

But i have added a job in AppServiceProvider.php:
public function boot()
	{
        \Event::listen('cron.collectJobs', function() {

            \Cron::add('example1', '* * * * *', function() {
                // Do some crazy things unsuccessfully every minute
                return 'Ok';
            });
        });
	}

The command > php artisan cron:run 
+------------+---------+----------+--------+------+
| Run date   | In time | Run time | Errors | Jobs |
+------------+---------+----------+--------+------+
| 1427130486 | -1      | 0        | 0      | 0    |
+------------+---------+----------+--------+------+
X-Powered-By: PHP/5.6.5
Content-type: text/html; charset=UTF-8

In laravel 4 everything works fine.

**Comment by liebig** [comment]
Hi @damage838,

I am sorry for this issue, but the Cron list command should work in Laravel 5, too. Did you add `'Liebig\Cron\Laravel5ServiceProvider'` to your `'providers'` array in the `/path/to/laravel/config/app.php` file? And please add your Cron code to the `/path/to/laravel5/app/Providers/AppServiceProvider.php` file at the `boot` method:

`/path/to/laravel5/app/Providers/AppServiceProvider.php`
```php
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider {

    //...

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot() {
        // Please note the different namespace 
        // and please add a \ in front of your classes in the global namespace
        \Event::listen('cron.collectJobs', function() {

            \Cron::add('example1', '* * * * *', function() {
                // Do some crazy things unsuccessfully every minute
                return 'No';
            });

            \Cron::add('example2', '*/2 * * * *', function() {
                // Do some crazy things successfully every two minute
                return null;
            });

            \Cron::add('disabled job', '0 * * * *', function() {
                // Do some crazy things successfully every hour
            }, false);
        });
    }
}
```

`php artisan cron:list`
```
+--------------+-------------+-----------+
| Jobname      | Expression  | Activated |
+--------------+-------------+-----------+
| example1     | * * * * *   | Enabled   |
| example2     | */2 * * * * | Enabled   |
| disabled job | 0 * * * *   | Disabled  |
+--------------+-------------+-----------+
```

I hope this helps.

**Comment by damage838** [comment]
Yeah that is exactly what i did.

providers array:
<pre>
'Illuminate\Validation\ValidationServiceProvider',
		'Illuminate\View\ViewServiceProvider',
        'Illuminate\Workbench\WorkbenchServiceProvider',
        'Liebig\Cron\Laravel5ServiceProvider',
		/*
		 * Application Service Providers...
		 */
		'App\Providers\AppServiceProvider',
</pre>
AppServiceProvider.php

<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider {

	/**
	 * Bootstrap any application services.
	 *
	 * @return void
	 */
	public function boot()
	{
        \Event::listen('cron.collectJobs', function() {

            \Cron::add('example1', '* * * * *', function() {
                // Do some crazy things unsuccessfully every minute
                return 'Ok';
            });
        });
	}

	/**
	 * Register any application services.
	 *
	 * This service provider is a great spot to register your various container
	 * bindings with the application. As you can see, we are registering our
	 * "Registrar" implementation here. You can add your own bindings too!
	 *
	 * @return void
	 */
	public function register()
	{
		$this->app->bind(
			'Illuminate\Contracts\Auth\Registrar',
			'App\Services\Registrar'
		);
	}

}

**Comment by liebig** [comment]
I have tried your code and for me this works great:
```
+----------+------------+-----------+
| Jobname  | Expression | Activated |
+----------+------------+-----------+
| example1 | * * * * *  | Enabled   |
+----------+------------+-----------+
```
Did you run `php artisan cron:list` from the `/path/to/laravel5/` directory? Which operating system are you using? Does the Cron job scheduling work but only the `cron:list` command does not?

**Comment by liebig** [comment]
Closed due to inactivity

**Comment by DanielRTRD** [comment]
I have the same problem. It worked the first couple of times with original code from docs.
![01-02-2016 02_02_00](https://cloud.githubusercontent.com/assets/9788214/12706535/f80f6290-c887-11e5-8d2d-f2fe9e31bf6c.png)

**Comment by DanielRTRD** [comment]
My problem is that the crons dont run.

**Comment by DanielRTRD** [comment]
After some more testing I found out that the cron.lock file in /storage was causing the hault. But the cron was also running at a to fast interval. Set it to one/two minutes and it worked much better.
