### ISSUE TITLE
Local time support ?

### ISSUE THREAD

**Issue by pierrerigal** [liebig/cron#64]
Actually we can set crons on UTC time, but here in france we are UTC+1 or UTC+2 depending of the season, so how can I set crons in local time format ?

Eg :  "0 7 * * * " will run at 6 or 7 UTC depending of the season but at 7 here in France !

Thanks for your help.

**Comment by liebig** [comment]
You can change your timezone at the `config/app.php` file at the `'timezone'` key. This should change the Cron time as well.

**Comment by liebig** [comment]
@pierrerigal do you still have problems with the timezone?

**Comment by liebig** [comment]
Closed due to inactivity.
