### ISSUE TITLE
artisan error

### ISSUE THREAD

**Issue by nosun** [liebig/cron#65]
when I composer install the package and add service provider in app.php , then run php artisan ,I got an error like this 

 [BadMethodCallException]            
  Call to undefined method [package]

I comment service provider  from app.php, its ok! 

may something wrong,framework now includes a number of generators out of the box.

**Comment by liebig** [comment]
If you receive this message, you are using the wrong service provider.
For Laravel 5, please add add 'Liebig\Cron\Laravel5ServiceProvider'.
For Laravel 4, please add 'Liebig\Cron\CronServiceProvider'

**Comment by nosun** [comment]
yes,it is my fault, Thanks for your reply

**Comment by liebig** [comment]
You are welocme.
