### ISSUE TITLE
runtime Cron_manager -1.00

### ISSUE THREAD

**Issue by h-rafiee** [liebig/cron#66]
Hello my friends.
this is my last cron_job
![cron_run](https://cloud.githubusercontent.com/assets/1610989/7782872/7c56c9ee-0141-11e5-89c9-4d4bbc2c4142.jpg)
ok last time work as well but now
all times of cron_manager runtime return -1.00
any help how can i fix this ?!

![cron_manager](http://s6.picofile.com/file/8189852476/asddffffff6666.jpg)

**Comment by liebig** [comment]
Hi,
have a look at the FAQ section of the [REAMDE file](https://github.com/liebig/cron#cron-is-not-running-properly-and-returns-runtime-and-intime-with-value--1). It seems that the `cron.lock` file was not deleted the last time and Cron prevents overlapping now. Just delete the lock file or disable overlapping with `\Cron::setDisablePreventOverlapping();`.

**Comment by liebig** [comment]
Hi @h-rafiee,
Does this problem still exist or can I close this issue?

**Comment by h-rafiee** [comment]
yes its done :+1: thanks to you my friend

**Comment by liebig** [comment]
Thanks for your reply. You are welcome!
