### ISSUE TITLE
Error composer update laravel 4

### ISSUE THREAD

**Issue by xeroky** [liebig/cron#69]
*** Edit
Fixed! with composer self-update :(

Any idea?

[RuntimeException]
Could not load package classpreloader/classpreloader in http://packagist.or
g: [UnexpectedValueException] Could not parse version constraint ^1.2.2: In
valid version string "^1.2.2"

[UnexpectedValueException]
Could not parse version constraint ^1.2.2: Invalid version string "^1.2.2"

**Comment by liebig** [comment]
Thank you for your feedback. As this is fixed I will close this issue.
