### ISSUE TITLE
Cron doesn't work

### ISSUE THREAD

**Issue by uekyo** [liebig/cron#70]
I set the cron belong this site.
But cron doesn't work.

[global.php]
Event::listen('cron.collectJobs', function() {
    Cron::add('getuser', '*/10 * * * *', function() {
        Log::info('Hey Kyo!');
        $params = array(1);
        $request = Request::create('gfp/ig', 'GET', $params);
        Route::dispatch($request)->getContent();
        return null;
    });
});

[command]
$ /usr/bin/php artisan cron:run

[results]
+------------+---------+----------+--------+------+
| Run date   | In time | Run time | Errors | Jobs |
+------------+---------+----------+--------+------+
| 1434820757 | false   | 0.0001   | 0      | 0    |
+------------+---------+----------+--------+------+

but getuser cron doesn't work.
Why it doesn't work??

**Comment by liebig** [comment]
Did your execute the command `/usr/bin/php artisan cron:run` on minute 0, 10, 20, 30, 40, 50? Because your expression is for every 10 minutes. So if you call the run command for example at 8:08 o'clock, the job won't be executed. But if you run it at 8:10 o'clock, the job will be executed.

**Comment by liebig** [comment]
Closed due to inactivity.
