### ISSUE TITLE
Laravel Command and Cron

### ISSUE THREAD

**Issue by icemanblas** [liebig/cron#75]
Hi,
I have Laravel command and I want to execute it with cron job. Here's the code:
```php
<?php namespace App\Console\Commands;

// ...

class TestCommand extends Command {
    protected $name = 'test';
    // ...
    public function fire() {
        // code goes here
    }
    ...
}
```

I want to be able to execute this command with cron job. How do I do this? Thanks in advance.

**Comment by liebig** [comment]
Hi,
Please try to call the Artisan command via code. For example:
```PHP
$exitCode = Artisan::call('email:send', [
    'user' => 1, '--queue' => 'default'
]);
```
You can find more details at the [Laravel documentation](http://laravel.com/docs/master/artisan#calling-commands-via-code).

**Comment by icemanblas** [comment]
Thanks a lot, I must have missed it.
