### ISSUE TITLE
Cron job running only one time

### ISSUE THREAD

**Issue by gabazureus** [liebig/cron#84]
Hello liebig, I am trying to use your lib to send automatic emails but I am having trouble with it. I want to send an email every minute, like in the code bellow

first:
I have a Controller that calls this:

```
    \Cron::setDisablePreventOverlapping();

    \Cron::add('example' . $times, '* * * * *', function() use($scriptStr, $nome, $subject) {

        Mail::send('emails.send', ['content' => $scriptStr], function ($message) use ($nome, $subject)
        {

            $message->from('from@test.com', 'teste');

            $message->to('to@test.com', $nome)->subject($subject);

        });

        return true;

    });

    \Cron::run();
```

than I have executed this command:

`* * * * * /usr/bin/php /var/www/guru/artisan schedule:run >> /var/www/guru/cronlog 2>&1`

To run the laravel schedule in every minute (and Its working, because is saving to cronlog file).

So I changed the schedule method in Kernel.php to this:

`
    protected function schedule(Schedule $schedule)
    {
        \Artisan::call('cron:run', array());
    }
`

But when the Controller runs the code, it creates a row in table **cron_job** and **cron_manager** but only run a single time, sending only one email.

Do you know what is wrong with this?

**Comment by liebig** [comment]
Do you get some log messages?

**Comment by liebig** [comment]
Maybe the lock file was not deleted and prevent overlapping is enabled. So please check your log file and reply.

From the readme:

## Cron is not running properly and returns runtime and inTime with value -1

By default Cron prevents overlapping. This means that only one Cron instance will run at the same time. If another instance is called, Cron will not run and will return the runtime and inTime parameter with the value -1. On some Windows machines the deletion of the lock file fails and you have to disable this feature.

**Comment by liebig** [comment]
Closed due to inactivity.
