### ISSUE TITLE
Pull request #80 not in composer package

### ISSUE THREAD

**Issue by larsbo** [liebig/cron#85]
The PR #80 that fixed the `cron:list`command in Laravel >= 5.2 installations is not in the latest composer release `1.1.1`.
Can you update it? 😃

**Comment by liebig** [comment]
Whoops, you are right! I just released the new version `1.1.2` with all changes. Please test.

**Comment by larsbo** [comment]
Thank you, cmposer installed version 1.1.2 and the command works fine!

**Comment by liebig** [comment]
Thank you for your reply.
