### ISSUE TITLE
Which user should run cron

### ISSUE THREAD

**Issue by wyklif** [liebig/cron#87]
Hi, so.. when i do a sudo crontab -e the cronjob seems to run but if i create the cron job under another user thats not root the cronjob doesnt seem to run. secondly my code for my cronjob doesnt execute however when i plug the code to the constructor for one of my controllers it runs i do not know what i am doing wrong

**Comment by liebig** [comment]
The user which run the command `/usr/bin/php /var/www/laravel/artisan cron:run` of course needs the user rights to run the php process and needs file rights for the `/var/www/laravel` directory. Please follow the example and put the jobs in the `AppServiceProvider.php` file.

**Comment by liebig** [comment]
Closed due to inactivity.
