### ISSUE TITLE
laravel5.2.45 install failed

### ISSUE THREAD

**Issue by Martin0709** [liebig/cron#90]
Hello, my laravel version is 5.2.45, but i composer require failed, this is error message:
Using version ^1.1 for liebig/cron
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - Can only install one of: laravel/framework[v5.2.43, v5.2.45].
    - don't install laravel/framework v5.2.45|remove illuminate/cache v5.2.43
    - don't install illuminate/cache v5.2.43|don't install laravel/framework v5.2.45
    - don't install illuminate/cache v5.2.43|don't install laravel/framework v5.2.45
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].
    - Installation request for illuminate/cache (locked at v5.2.43) -> satisfiable by illuminate/cache[v5.2.43], laravel/framework[v5.2.43].

Installation failed, reverting ./composer.json to its original content.

and it's my composer.json file content
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "barryvdh/laravel-debugbar": "^2.2",
        "zizaco/entrust": "5.2.x-dev",
        "illuminate/html": "^5.0",
        "laravelcollective/html": "~5.0",
        "mews/captcha": "~2.0",
        "barryvdh/laravel-ide-helper": "^2.1",
        "maatwebsite/excel": "~2.1.0",
        "vinkla/hashids": "^3.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "stable",
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packagist.phpcomposer.com"
        }
    }
}

**Comment by Martin0709** [comment]
sorry , i solved by command "composer update"

**Comment by liebig** [comment]
Very nice to hear that everything is working. Thanks for your reply.
