### ISSUE TITLE
passing variable to the function parameter before adding a cron

### ISSUE THREAD

**Issue by franzlocksoftwares** [liebig/cron#91]
Hi, is there a way to pass an outside variable before adding a cron to the 3rd parameter(the function parameter) without changing anything inside the package?

i have this kind of code:

while(someloop){
$variable_from_outside=0;
$variable_from_outside++;
\Cron::add('samplecron', '* * * * *', function() {
    echo $variable_from_outside;
 }, false);
}
------------------

as you can see, the $variable_from_outside is from outside, and it turns out that i couldnt use it inside the function argument.. is there a clever way to use the outsidevariable inside the function? sorry, this kind of problem its kinda new to me.

**Comment by liebig** [comment]
Hi, yes, `[...] within user-defined functions a local function scope is introduced. Any variable used inside a function is by default limited to the local function scope.` Please have a look at the [Variable scope  documentation](http://php.net/manual/en/language.variables.scope.php).
This should help:
```php
use Illuminate\Support\Facades\Log;
...
while(someloop){
	$variable_from_outside=0;
	$variable_from_outside++;
	\Cron::add('samplecron', '* * * * *', function() {
                global $variable_from_outside;
		Log::info('$variable_from_outside: '.$variable_from_outside);
	}, false);
}
```
or maybe
```php
use Illuminate\Support\Facades\Log;
...
while(someloop){
	$variable_from_outside=0;
	$variable_from_outside++;
	\Cron::add('samplecron', '* * * * *', function(&$variable_from_outside) {
		Log::info('$variable_from_outside: '.$variable_from_outside);
	}, false);
}
```
This [Stackoverflow entry](http://stackoverflow.com/questions/13708959/php-global-variables-not-working-inside-a-function) could help, too.

**Comment by franzlocksoftwares** [comment]
Hmm.. ive tried both solution just now.. seems theyre still not working as expected..
1st solution turns out to be just initializing the variable inside the function..
2nd solution gives this error
![image](https://cloud.githubusercontent.com/assets/15091191/25472497/13843994-2b5e-11e7-99bb-411bf9054d64.png)

we've also tried to use private class variables, but still no luck. i have some idea now on how i could pass an outside variable, but it includes some modification in the codes in the package(which is as much as posible i would like to avoid.).

**Comment by liebig** [comment]
Ah I see. The second solution does not work, because I call the function without Parameters (`$return = $job['function']();`).  Please try the `use` keyword.

```php
use Illuminate\Support\Facades\Log;
...
while(someloop){
	$variable_from_outside=0;
	$variable_from_outside++;
	\Cron::add('samplecron', '* * * * *', function() use ($variable_from_outside) {
		Log::info('$variable_from_outside: '.$variable_from_outside);
	}, false);
}
```

**Comment by franzlocksoftwares** [comment]
ah thats it.. it works now! i ddint even know that was possible.. thanks! 
im so sorry, its my first time encountering this kind of problem and solution. but thanks a lot, its a new learning for me..

**Comment by liebig** [comment]
You are welcome :)
