### ISSUE TITLE
Php artisan cron:run Not working

### ISSUE THREAD

**Issue by tanmaysakhale24** [liebig/cron#93]
After running php artisan cron:run
It shows
PHP Warning:  Module 'pgsql' already loaded in Unknown on line 0                                                          
  [ReflectionException]                                   
  Method Liebig\Cron\RunCommand::handle() does not exist 

After running any command list,run and keygen. i got the same error.
Please help me with this issue

**Comment by liebig** [comment]
Which version of Laravel are you using? Did you [installed Cron as described in the manual](https://github.com/liebig/cron#installation)?

**Comment by tanmaysakhale24** [comment]
Laravel Framework 5.5.2
Installed as same in the documentation. Cron::add function is working fine for me and records are getting updated in cron_job and cron_manager.
One more issue i have
I want to make the cron function (Basic insert query for testing like inserting 10000 records in table)  timeout after 30 sec of execution time. But script continue to run for 48 sec successfully. I want to store the timeout error in cron_job.
I made changes in etc/php/7.0/cli/php.ini file by changing max_execution_time= 3 and changing max_input_time=3. But then also cron continue to complete its script, is there any way i can put a timeout limit to cron::add or any other options u have

**Comment by liebig** [comment]
Maybe this can help: [How do you set max execution time of PHP's CLI component?](https://serverfault.com/questions/283397/how-do-you-set-max-execution-time-of-phps-cli-component)

**Comment by tanmaysakhale24** [comment]
This helped me thanks. It is generating a fatal error and that error is not getting stored in cron_job table.

Help me with this issue too
After running php artisan cron:run
It shows
PHP Warning: Module 'pgsql' already loaded in Unknown on line 0
[ReflectionException]
Method Liebig\Cron\RunCommand::handle() does not exist

After running any command list,run and keygen. i got the same error.

Completed Following steps.
Installing Fresh Laravel

laravel new cronproject
php artisan key:generate
creating database
changing env file with the DB details
php artisan migrate
Add "liebig/cron": "dev-master" to your /path/to/laravel/composer.json file at the "require": section (Find more about composer at http://getcomposer.org/)
Run the composer update liebig/cron --no-dev command in your shell from your /path/to/laravel/ directory
Add 'Liebig\Cron\Laravel5ServiceProvider' to your 'providers' array in the /path/to/laravel/config/app.php file
Migrate the database with running the command php artisan migrate --path=vendor/liebig/cron/src/migrations
Publish the configuration file with running the command php artisan vendor:publish - now you find the Cron configuration file at /path/to/laravel/config/liebigCron.php and this file won't be overwritten at any update

I am calling the cron from controller
http://127.0.0.1:8000/cron

        Cron::add('CreateUser', '* * * * *', function() {
            $cnt=5000;
            $saved="";
            for($i=0;$i<=$cnt;$i++) {
                $user = new User;

                $user->name = "tanmay" . rand();
                $user->email = 'tanmay.sakhale' . rand() . '@gmail.com';
                $user->password = 'password';
                $saved = $user->save();
            }
            if(!$saved){
                return "Error:421";
            } else {
                return "Success";
            }
        });        
        $report = Cron::run();
        print_r ($report);
    }

If i try it from AppServiceProvider by writing it on boot() function. How to call this cron automatically not having idea how to do this ??

Please help

**Comment by liebig** [comment]
This `Method Liebig\Cron\RunCommand::handle() does not exist` seems to be a namespace problem, because `Liebig\Cron\Run` does exist but `Liebig\Cron\RunCommand` does not. So please check your code! Please have a look at the README how to [use Cron's integrated route](https://github.com/liebig/cron#using-crons-integrated-route).

**Comment by tanmaysakhale24** [comment]
![image](https://user-images.githubusercontent.com/31241969/30276683-383175dc-9723-11e7-9bac-ae7f76c5a272.png)
This is showing when i am typing the command

**Comment by tanmaysakhale24** [comment]
![image](https://user-images.githubusercontent.com/31241969/30278605-75013fba-9728-11e7-92a9-1965b80e16df.png)
Now my cron started running by the run command. I checked it in the cron_job table. 

Just i am not able to see list command. I am doing print_r to see the list of cron jobs.
How to solve this ReflectionException
Thanks for your help

**Comment by liebig** [comment]
Can you please test to rename (in vendor directory) `cron/src/Liebig/Cron/ListCommand.php` line 37 
```php
public function fire() {
```
to
```php
public function handle() {
```
and try the `cron:list` command again?
Thank you.

**Comment by tanmaysakhale24** [comment]
It started working. Thank you for the help.

**Comment by liebig** [comment]
Okay, then we have to change all the `fire` method names to `handle` for the command files. A PR would be awesome.

**Comment by liebig** [comment]
I added a [Pull Request](https://github.com/liebig/cron/pull/94) for this issue. Please have a look at it and test it. You can download the [laravel-5.5 branch](https://github.com/liebig/cron/archive/laravel-5.5.zip) and extract it to your vendor directory (or only the three command files `KeygenCommand.php`, `ListCommand.php` and `RunCommand.php`) and execute the commands.  Thank you.

**Comment by liebig** [comment]
I have tested the changes and they seem to work. PR is merged and closed.

**Comment by tanmaysakhale24** [comment]
Ok I will try
