### ISSUE TITLE
[Laravel 5.6] Ambiguous class resolution warning

### ISSUE THREAD

**Issue by larsbo** [liebig/cron#98]
Since version 5.6 Laravel has `dragonmantank/cron-expression` as dependency which is a fork of `mtdowling/cron-expression`:
https://github.com/laravel/framework/blob/5.6/composer.json#L22

This results in a lot of `Ambiguous class resolution` warnings during composer package auto discovery, 
when this package is also installed.

**Comment by liebig** [comment]
Thank you for the information. I would suggest that we tag the current version as 1.3 and then only support Laravel > 5.6 for the 2.0 release. We could remove all backward compatibilities, as well as the dependence to "mtdowling/cron-expression". What do you think of the idea?

**Comment by larsbo** [comment]
@liebig some updates here? 😺

**Comment by liebig** [comment]
No, not really. Since the used Cron-Expression Framework is not developed any more (https://github.com/mtdowling/cron-expression/issues/169) I have to think about something here....

**Comment by larsbo** [comment]
Why not replacing it with the fork `dragonmantank/cron-expression`?

**Comment by liebig** [comment]
Oh, I didn't see that fork existed. I'll do that, too. Thanks for the tip.

**Comment by larsbo** [comment]
You already merged a pull request that fixed the problem: https://github.com/liebig/cron/pull/95 😄 
I think you just forgot to release a new version including the fix.

**Comment by liebig** [comment]
Oh wow, you might be right! Could you check out and test the Master Branch? Then I would make a new release.

**Comment by larsbo** [comment]
works fine with "dev-master" in Laravel 5.8 👍

**Comment by liebig** [comment]
Great, thank you so much for your support. I've just created and released version 1.3 and I've just synchronized it with Packagist.
