### ISSUE TITLE
doesn't work with Laravel 5.8

### ISSUE THREAD

**Issue by larsbo** [liebig/cron#99]
the `fire()` method in the event class has been removed in Laravel 5.8: https://laravel.com/docs/5.8/upgrade

> The fire Method
> Likelihood Of Impact: Low
> The fire method (which was deprecated in Laravel 5.4) of the Illuminate\Events\Dispatcher class has been removed. You should use the dispatch method instead.

**Comment by liebig** [comment]
Are the Laravel Commands not working anymore or does the error occur when running Cron?

**Comment by larsbo** [comment]
The cron running failed. I think you just have to replace all `\Event::fire()` calls with `\Event::dispatch()` calls like in https://github.com/liebig/cron/blob/2a9806b40a063c873f067c00b77cb33fe117e705/src/Liebig/Cron/RunCommand.php#L48

**Comment by liebig** [comment]
Okay, thank you for the analysis. Maybe you can [create a Pull Request](https://help.github.com/en/articles/creating-a-pull-request)?

**Comment by larsbo** [comment]
The change will end support for Laravel <= 5.2: https://github.com/kristijanhusak/laravel-form-builder/issues/492#issuecomment-471210754
Should this be handled by composer requirement?

**Comment by liebig** [comment]
With the `require` keyword you rather define external dependencies which are then automatically added to the project. Therefore I would suggest that we write in the README at the Patch Notes that we only support Laravel >5.2 after this version.

**Comment by anonymusbg** [comment]
Liebig version higher 1.2 doesn't support Laravel 5.2 (as it's stated above) and you are getting this error: `Call to undefined method Illuminate\Events\Dispatcher::dispatch()` to fix this adjust your composer.json and instead of "dev-master" place "1.2", run composer update and enjoy.
